[package]
name = "fractal"
version = "0.1.0"
authors = ["Damien Castelltort <dcastelltort@gmail.com>"]

[dependencies]
byteorder = "1.1.0"
num = "0.1.40"
clap = "2.27.1"
serde = "1.0.21"
serde_json = "1.0.6"
serde_derive = "1.0.21"
crossbeam = "0.3.0"
hprof = "0.1.3"
